import os
import json
import structlog
from typing import Dict, Any

logger = structlog.get_logger(__name__)

# Default DealForge AI theme
DEFAULT_THEME = {
    "primary_color": "#003A70",
    "secondary_color": "#0072CE",
    "accent_color": "#00B4D8",
    "font_family": "Helvetica",
    "logo_path": "assets/dealforge_logo.png",
    "disclaimer_text": "CONFIDENTIAL - Auto-generated by DealForge AI.",
}


def load_custom_branding(tenant_id: str) -> Dict[str, Any]:
    """
    Load custom branding configuration for a specific tenant/user.
    """
    branding_file = os.path.join(
        os.path.dirname(__file__), f"../../data/branding/{tenant_id}.json"
    )

    if not os.path.exists(branding_file):
        return DEFAULT_THEME.copy()

    try:
        with open(branding_file, "r", encoding="utf-8") as f:
            custom_theme = json.load(f)
            # Merge with default to ensure all keys exist
            theme = DEFAULT_THEME.copy()
            theme.update(custom_theme)
            return theme
    except Exception as e:
        logger.error("branding_load_error", tenant_id=tenant_id, error=str(e))
        return DEFAULT_THEME.copy()


def apply_branding_to_reportlab(styles: dict, theme: dict) -> dict:
    """
    Modifies ReportLab styles dict based on custom branding.
    """
    from reportlab.lib import colors

    primary = theme.get("primary_color", "#003A70")
    secondary = theme.get("secondary_color", "#0072CE")

    if "CoverTitle" in styles:
        styles["CoverTitle"].textColor = colors.HexColor(primary)
    if "SectionTitle" in styles:
        styles["SectionTitle"].textColor = colors.HexColor(primary)
    if "AgentHeader" in styles:
        styles["AgentHeader"].textColor = colors.HexColor(secondary)

    return styles
