import os
import json
import structlog
from typing import Dict, Any

logger = structlog.get_logger(__name__)

from pydantic import BaseModel, Field

class BrandingConfig(BaseModel):
    primary_color: str = "#003A70"
    secondary_color: str = "#0072CE"
    accent_color: str = "#00B4D8"
    font_family: str = "Helvetica"
    logo_path: str = "assets/dealforge_logo.png"
    disclaimer_text: str = "CONFIDENTIAL - Auto-generated by DealForge AI."

# Default DealForge AI theme
DEFAULT_THEME = BrandingConfig()

MBB_THEME = BrandingConfig(
    primary_color="#051C2C",
    secondary_color="#00ADEE",
    accent_color="#F2F2F2"
)

GOLDMAN_THEME = BrandingConfig(
    primary_color="#7399C6",
    secondary_color="#003567",
    accent_color="#D8CECC"
)


def load_custom_branding(tenant_id: str) -> BrandingConfig:
    """
    Load custom branding configuration for a specific tenant/user or preset.
    """
    if tenant_id == "mbb":
        return MBB_THEME
    if tenant_id == "goldman":
        return GOLDMAN_THEME

    branding_file = os.path.join(
        os.path.dirname(__file__), f"../../data/branding/{tenant_id}.json"
    )

    if not os.path.exists(branding_file):
        return DEFAULT_THEME

    try:
        with open(branding_file, "r", encoding="utf-8") as f:
            custom_data = json.load(f)
            return BrandingConfig(**custom_data)
    except Exception as e:
        logger.error("branding_load_error", tenant_id=tenant_id, error=str(e))
        return DEFAULT_THEME


def apply_branding_to_reportlab(styles: Any, theme: BrandingConfig) -> Any:
    """
    Modifies ReportLab styles dict based on custom branding.
    """
    from reportlab.lib import colors

    primary = theme.primary_color
    secondary = theme.secondary_color

    if "CoverTitle" in styles:
        styles["CoverTitle"].textColor = colors.HexColor(primary)
    if "SectionTitle" in styles:
        styles["SectionTitle"].textColor = colors.HexColor(primary)
    if "AgentHeader" in styles:
        styles["AgentHeader"].textColor = colors.HexColor(secondary)
    if "BodyTextCustom" in styles:
        styles["BodyTextCustom"].fontName = theme.font_family

    return styles
